# Generated by Django 2.1.1 on 2018-09-19 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lender_books', '0002_book_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='user_id',
            new_name='user',
        ),
    ]
